

INSERT INTO ESTADO(ESTADO_ID,ESTADO_NOMBRE)VALUES(1, 'Registrado');
INSERT INTO ESTADO(ESTADO_ID,ESTADO_NOMBRE)VALUES(2, 'Retirado');



INSERT INTO TIEMPO(TIEMPO_ID,TIEMPO_NOMBRE)VALUES(1, 'Dia');
INSERT INTO TIEMPO(TIEMPO_ID,TIEMPO_NOMBRE)VALUES(2, 'Hora');




INSERT INTO CLASE_AUTOMOTOR(CLASE_ID,CLASE_NOMBRE)VALUES(1, 'Carro');
INSERT INTO CLASE_AUTOMOTOR(CLASE_ID,CLASE_NOMBRE)VALUES(2, 'Moto');



INSERT INTO TARIFA(TARIFA_ID,CLASE_ID,TIEMPO_ID,TARIFA_VALOR)VALUES(1,1,1,8000);
INSERT INTO TARIFA(TARIFA_ID,CLASE_ID,TIEMPO_ID,TARIFA_VALOR)VALUES(2,1,2,1000);
INSERT INTO TARIFA(TARIFA_ID,CLASE_ID,TIEMPO_ID,TARIFA_VALOR)VALUES(3,2,1,4000);
INSERT INTO TARIFA(TARIFA_ID,CLASE_ID,TIEMPO_ID,TARIFA_VALOR)VALUES(4,2,2,500);




