spring:
  application:
    name: servicio-parqueadero

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/bd_parqueadero?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
